spring.application.name=buildex-backend

# ===============================
# DATABASE (NEON - CORRECT)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-muddy-frog-a1yhyqva-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&ssl=true
spring.datasource.username=neondb_owner
spring.datasource.password=npg_beJnP9q4ZMvk
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# EMAIL (RESEND API)
# ===============================
resend.api.key=re_isWBNR3v_Dfsw1V2yzQc57ykm4SA8WTJa
resend.api.url=https://api.resend.com/emails

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# PERFORMANCE (GZIP)
# ===============================
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024


# ===============================
# FRONTEND URL (For Share Redirects)
# ===============================
app.frontend.url=http://localhost:5173
