spring.application.name=buildex-backend

# ===============================
# DATABASE (NEON POSTGRES - HARDCODED)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-autumn-boat-a1uh07y9-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&tcpKeepAlive=true
spring.datasource.username=neondb_owner
spring.datasource.password=npg_lmNUcGdwtf62
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# HIKARI POOL (NEON SAFE)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# SERVER (RENDER SAFE)
# ===============================
server.port=8080
server.address=127.0.0.1

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=INFO

# ===============================
# EMAIL (HARDCODED – GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=visodiyadhyey@gmail.com
spring.mail.password=yrucbskkvaithvex
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# PERFORMANCE (GZIP)
# ===============================
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024
